### web
server:
  port: 7000
  servlet:
    context-path:

  ### actuator
management:
  server:
    servlet:
      context-path: /actuator
  health:
    mail:
      enabled: false

### resources
spring:
  application:
    name: task_manager
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern:  /static/**
  resources:
    static-locations: classpath:/static/
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: utf-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
  datasource:
    url: jdbc:mysql://47.99.40.220:3306/xxl_job?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Aa111111
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

xxl:
  job:
    accessToken:
    i18n:
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
    logretentiondays: 30

mybatis:
    mapper-locations: classpath:/mybatis-mapper/*Mapper.xml
    type-aliases-package: cn.imacoder.taskscheduler.manager.core.model.*

logging:
  config: classpath:logback.xml
